### ISSUE TITLE
On server start, I'm not seeing port 2456 and 2457 open in netstat

### ISSUE THREAD

**Issue by Psilovybin** [akridge/Oracle-Cloud-Free-Valheim-Game-Server-Setup#3]
Regardless of the Firewall settings, i'm not seeing 2456 and 2457 UDP open in netstat.  Port 22 is open and I can see it from here, but the server will not open 2456 and 2457.  I have the firewall rules in place.  even setup 27800 and 27801 and it won't open those up.  I'm wondering if this is a group permissions thing.  going to try that now

**Comment by Psilovybin** [comment]
Ok, it was latching onto to 2456 UDP6 and 2457 UDP
Disabled ipv6 in grub and now it's latching onto 2456 UDP

**Comment by akridge** [comment]
Happy to hear its working. Cheers.
