### ISSUE TITLE
Readme table not up to date

### ISSUE THREAD

**Issue by burgil** [akridge/Oracle-Cloud-Free-Valheim-Game-Server-Setup#4]
It states that the free tier comes with 1gb ram but in oracle free tier it says we can get up to 4cpu and 24gb ram linux machines
but they use ARM, is that a problem?
https://www.oracle.com/il-en/cloud/free/

**Comment by akridge** [comment]
Hey!

Yeah sadly I've let this get out of date a bit. Been wanting to make an updated version, but been busy. 

But yeah Oracle free tier is great. They now give users even more free resources like you noted. 

ARM isn't a problem at all and I would totally recommend taking advantage of it. Before it was really the RAM holding back the free tier, but now that free tier cpu/ram offering is great. 

Cheers!
Michael

**Comment by burgil** [comment]
Cheers!
Thanks Michael!
